version: "3.9"

services:
  feature-detection-service:
    build: .
    container_name: limelight-feature-detection-service
    restart: always
    user: "${UID}:${GID}"
    ports:
      - "${HOST_MACHINE_WEBAPP_PORT}:${WEBAPP_PORT}"
    labels:
      - traefik.enable=false
    environment:
      SPECTR_GET_SCAN_DATA_URL: ${SPECTR_GET_SCAN_DATA_URL}
      WEBAPP_PORT: ${WEBAPP_PORT}
      SPECTR_BATCH_SIZE: ${SPECTR_BATCH_SIZE}
    volumes:
      - type: bind
        source: ${HOST_MACHINE_FINAL_DIR}
        target: /data/app/finaldir
        read_only: false
      - type: bind
        source: ${HOST_MACHINE_WORKDIR}
        target: /data/app/workdir
        read_only: false
